"""
AMD GPU specifications and best practices for prompt construction.

This file is intentionally simple and uses dictionaries so it can be exec()'d
like the NVIDIA GPU spec file.
"""

AMD_GPU_SPEC_INFO = {
    # Based on provided rocminfo for AMD Radeon 9700 (gfx1201)
    "R9700": {
        "GPU Name": "AMD Radeon 9700 (gfx1201)",
        "GPU Architecture": "AMD RDNA4 (gfx1201)",
        "Compute Units": 64,
        "SIMDs per CU": 2,
        "Shader Engines": 4,
        "Shader Arrays per Engine": 2,
        "Wavefront Size": "Wave32",
        "Max Clock (MHz)": 2350,
        "Workgroup Max Size": 1024,
        "Max Waves per CU": 32,
        "Stream Processors": 4096,
        "Ray Accelerators": 64,
        "AI Accelerators": 128,
        "ROPs": 128,
        "Transistors": "53.9 Billion",
        "Peak Pixel Fill Rate": "373.76 GP/s",
        "L1 Cache": "32 KB",
        "L2 Cache": "8 MB",
        "L3 Cache": "64 MB",
        "Cacheline Size": "256 B",
        "LDS (Workgroup Local Memory)": "64 KB",
        "VRAM": "32,061,259,776 B (~29.85 GiB)",
        "Memory Bandwidth": "Unknown",
        "FP32 Vector TFLOPS": "47.8",
        "FP16 Vector TFLOPS": "95.7",
        "FP16 Matrix TFLOPS": "191 (383 w/ sparsity)",
        "FP8 Matrix TFLOPS": "383 (766 w/ sparsity)",
        "INT8 Matrix TOPS": "383 (766 w/ sparsity)",
        "INT4 Matrix TOPS": "766 (1531 w/ sparsity)",
        "Max Registers per Block": 196608,
        "Max Shared Memory per Block": 65536,
        "Max Threads per Block": 1024,
        "Max Threads per CU": 2048,
        "Shared Memory per CU": 2097152,
        "Warp Size": 32,
        "MFMA": "Unknown",
    }
    ,
    # Based on provided rocminfo for AMD Instinct MI355X (gfx950)
    "MI355X": {
        "GPU Name": "AMD Instinct MI355X (gfx950)",
        "GPU Architecture": "gfx950 (CDNA family)",
        "Compute Units": 256,
        "SIMDs per CU": 4,
        "Shader Engines": 32,
        "Shader Arrays per Engine": 1,
        "Wavefront Size": "Wave64",
        "Max Clock (MHz)": 2400,
        "Peak Engine Clock": "2.4 GHz",
        "Workgroup Max Size": 1024,
        "Max Waves per CU": 32,
        "Max Work-item per CU": 2048,
        "Matrix Cores": 1024,
        "Stream Processors": 16384,
        "L1 Cache": "32 KB",
        "L2 Cache": "4 MB",
        "L3 Cache": "256 MB",
        "Cacheline Size": "128 B",
        "LDS (Workgroup Local Memory)": "160 KB",
        "VRAM": "288 GB HBM3E (309,220,868,096 B)",
        "Memory Bandwidth": "8 TB/s",
        "Memory Interface": "8192 bits",
        "Infinity Cache (Last Level)": "256 MB",
        "FP16 Vector TFLOPS": "157.3",
        "FP16 Matrix PFLOPS": "2.5166 (5.0332 w/ sparsity)",
        "BF16 Matrix PFLOPS": "2.5166 (5.0332 w/ sparsity)",
        "INT8 Matrix POPS": "5.0332 (10.0664 w/ sparsity)",
        "MXFP8 PFLOPS": "5.0332",
        "OCP-FP8 PFLOPS": "5.0332 (10.0664 w/ sparsity)",
        "MXFP6 PFLOPS": "10.0663",
        "MXFP4 PFLOPS": "10.0663",
        "FP64 Vector TFLOPS": "78.6",
        "FP32 Vector TFLOPS": "157.3",
        "FP64 Matrix TFLOPS": "78.6",
        "FP32 Matrix TFLOPS": "157.3",
        "Max Registers per Block": 131072,
        "Max Shared Memory per Block": 163840,
        "Max Threads per Block": 1024,
        "Max Threads per CU": 2048,
        "Shared Memory per CU": 41943040,
        "Warp Size": 64,
        "MFMA": "Unknown",
    },

    # Based on provided rocminfo + HIP query for AMD Radeon PRO W7900D (gfx1100)
    "R7900": {
        "GPU Name": "AMD Radeon PRO W7900D (gfx1100)",
        "GPU Architecture": "AMD RDNA3 (gfx1100)",
        "Compute Units": 96,
        "SIMDs per CU": 2,
        "Shader Engines": 6,
        "Shader Arrays per Engine": 2,
        "Wavefront Size": "Wave32",
        "Max Clock (MHz)": 1760,
        "Workgroup Max Size": 1024,
        "Max Waves per CU": 32,
        "Max Work-item per CU": 1024,
        "L1 Cache": "32 KB",
        "L2 Cache": "6 MB",
        "L3 Cache": "96 MB",
        "Cacheline Size": "128 B",
        "LDS (Workgroup Local Memory)": "64 KB",
        "VRAM": "Unknown",
        "Memory Bandwidth": "Unknown",
        "Max Registers per Block": 196608,
        "Max Shared Memory per Block": 65536,
        "Max Threads per Block": 1024,
        "Max Threads per CU": 2048,
        "Shared Memory per CU": 3145728,
        "Warp Size": 32,
        "MFMA": "Unknown",
    },
    
}

AMD_GPU_DEFINITIONS = {
    "Wavefront": "AMD's SIMD execution group (Wave32 or Wave64).",
    "Wave32": "A 32-lane wavefront, common on RDNA architectures.",
    "Wave64": "A 64-lane wavefront, common on CDNA architectures.",
    "Compute Unit (CU)": "AMD's equivalent of an NVIDIA SM.",
    "Work-item": "A single thread in a kernel execution.",
    "Workgroup": "A group of work-items that can synchronize and share LDS.",
    "SIMD": "A SIMD unit inside a CU that executes a wavefront.",
    "LDS": "Local Data Share, AMD's shared memory.",
    "VGPR": "Vector registers allocated per work-item.",
    "SGPR": "Scalar registers shared across a wavefront.",
    "Occupancy": "Number of active waves per CU, limited by registers and LDS.",
    "Infinity Cache": "AMD's last-level cache that reduces DRAM traffic.",
    "MFMA": "Matrix Fused Multiply-Add instruction for matrix cores.",
    "Barrier": "A workgroup synchronization point.",
}

AMD_GPU_BEST_PRACTICES = [
    "Prefer Wave32-friendly configurations on RDNA architectures.",
    "Prefer Wave64 on CDNA unless the kernel benefits from Wave32.",
    "Choose workgroup sizes as multiples of the wavefront (32 or 64).",
    "Start with workgroup sizes in [256, 512, 1024] for 1D kernels.",
    "Balance VGPR usage and occupancy; avoid register spilling.",
    "Use LDS for data reuse; pad to avoid LDS bank conflicts.",
    "Keep global memory access contiguous and aligned (128B where possible).",
    "Use vectorized loads/stores when it improves bandwidth utilization.",
    "Use MFMA/matrix cores for GEMM-like operations when available.",
    "Minimize divergent branches within a wavefront.",
    "Avoid fp16 for exp/log; cast to fp32 for numerically sensitive ops.",
]
